### ISSUE TITLE
I'm getting `putIfAbsent` missing when running the connector in MSK Connect

### ISSUE THREAD

**Issue by isaacraja** [awslabs/eventbridge-kafka-connector#80] opened 2023-07-11 12:27 UTC
## Describe the bug
I'm getting this error when setting up eventbridge kafka connector on AWS MSK connect. I tried different AWS MSK cluster versions and different configurations. It's running fine when i create the connector in an EC2 instance. MSK connect runs in Kafka connect v2.7.1. I tried running msk cluster also with the same version but it didn't work. 

```[Worker-asdfadsf] Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonNode com.fasterxml.jackson.databind.node.ObjectNode.putIfAbsent(java.lang.String, com.fasterxml.jackson.databind.JsonNode)```
```at software.amazon.event.kafkaconnector.EventBridgeWriter.createJsonPayload```

**Comment by embano1** [comment] 2023-07-11 13:24
@isaacraja thx for reaching out! I'll consult with the MSK team and report back!

**Comment by isaacraja** [comment] 2023-07-11 16:47
Yes. I used with-dependencies.jar. I'm not bundling anything else with the plugin. Just the with-dependencies.jar file as a msk connect plugin and  created a msk connector using that plugin.

**Comment by embano1** [comment] 2023-07-11 20:01
Strange, will consult with the MSK Connect team as we tested the connector w/out problem.

> It's running fine when i create the connector in an EC2 instance

You mean running Kafka Connect on EC2? Btw: that error is a Java runtime error, not related to the connector at all, but we'll figure.

**Comment by isaacraja** [comment] 2023-07-12 00:42
Yeah, I ran Kafka connect in an EC2 instance and installed eventbridge-kafka-connector and no issues there. 

> Btw: that error is a Java runtime error, not related to the connector at all, but we'll figure.
Oh, ok. Thanks.

**Comment by isaacraja** [comment] 2023-07-12 07:41
Btw, I added `jackson-core-2.15.2.jar`, `jackson-databind-2.15.2.jar`, `jackson-annotations-2.15.2.jar` to the custom plugin, and it started working in MSK connect.

**Comment by embano1** [comment] 2023-07-12 07:45
> Btw, I added `jackson-core-2.15.2.jar`, `jackson-databind-2.15.2.jar`, `jackson-annotations-2.15.2.jar` to the custom plugin, and it started working in MSK connect. Thanks for the pointer.

Thank you for your feedback! I'll bring this up with the MSK team, but looks like you're good now? Happy streaming and let us know if you need something.

Btw: we're close to cutting our next release which improves batching.

**Comment by embano1** [comment] 2023-07-12 11:43
@isaacraja are we good to close this one then? Thx again for using the connector!

**Comment by embano1** [comment] 2023-09-04 14:41
@kristianhellum thx for reaching out (reopening this issue).

I have pinged the MSK team again, also looping in @maschnetwork and @agebhar1 for thoughts on our dependency on `jackson` here (@agebhar1 was planning to do some benchmarking in #39 before we remove this dependency/replace it with another solution).

**Comment by agebhar1** [comment] 2023-09-04 17:39
@isaacraja is using Kafka connect v2.7.1 released in [09/2021](https://www.instaclustr.com/blog/general-availability-of-apache-kafka-and-kafka-connect-2-7-1/) which ships an older version of Jackson. Jackson's version should be [2.10.x][https://mvnrepository.com/artifact/org.apache.kafka/connect-json/2.7.1]. The missing method `putIfAbsent` was introduced in Version 2.13.

@kristianhellum the drop of Jackson in AWS SDK has no impact on this issue. Jackson is included within a relocated package. 

> SDK Footprint Changes
> Because the SDK now includes its own “[shaded](https://maven.apache.org/plugins/maven-shade-plugin/)” copy of Jackson, the footprint (total jar size) of the SDK will change. ...

The Benchmark requires some effort in time.  @embano1, if it's urgent we can also include Jackson 'shaded'.

**Comment by embano1** [comment] 2023-09-04 19:21
> if it's urgent we can also include Jackson 'shaded'

I'm a bit reluctant to include that dependency in our JAR because 

- in sources/sinks it's generally recommended to exclude it (typically provided by the Connect framework)
- it can cause all sorts of troubleshooting issues that shaded deps bring, i.e., complicating troubleshooting/reproducibility of bug reports on our end
- it increases package size (ok, that's probably minor)

@kristianhellum I keep you posted on the MSK response. Anything else we can do for you here?

**Comment by kristianhellum** [comment] 2023-09-05 14:26
@embano1 Nothing more you can do for us now, thanks. We'll watch this issue and #39 , wait for your decision and act accordingly.

FYI I was told we are using Kafka 3.1 in the environment where the issue is occurring.

**Comment by embano1** [comment] 2023-09-07 11:28
@isaacraja @kristianhellum I created https://github.com/awslabs/eventbridge-kafka-connector/pull/123 which should fix the issue you're seeing. Once merged, I'll create a new `v1.1.1` release so you can deploy and verify.

**Comment by embano1** [comment] 2023-09-07 13:56
@isaacraja @kristianhellum new release https://github.com/awslabs/eventbridge-kafka-connector/releases/tag/v1.1.1

**Comment by embano1** [comment] 2023-09-07 13:56
Let us know if it fixes your issue

**Comment by kristianhellum** [comment] 2023-09-08 10:13
@embano1 
We have tested with v1.1.1 without adding the jackson dependencies, it indeed solved the problem for us. 
Thanks a lot 👍

**Comment by embano1** [comment] 2023-09-08 10:26
Fantastic! Going to resolve this then. Thx for your quick feedback 🙏

**Closed** 2023-09-08 10:26 UTC
Labels: bug
